/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        "tertiary-fixed": "#b3ebff",
        "surface-bright": "#f7f9fb",
        "surface-tint": "#006399",
        "on-tertiary": "#ffffff",
        "on-secondary": "#ffffff",
        "primary-fixed": "#cde5ff",
        "outline-variant": "#bfc7d1",
        "surface-container-lowest": "#ffffff",
        "on-primary-container": "#f3f7ff",
        "on-primary": "#ffffff",
        "surface-dim": "#d8dadc",
        "error-container": "#ffdad6",
        "secondary-fixed-dim": "#58d6f1",
        "on-primary-fixed": "#001d32",
        "inverse-surface": "#2d3133",
        "error": "#ba1a1a",
        "surface-container-low": "#f2f4f6",
        "on-tertiary-container": "#ecf9ff",
        "primary-container": "#0077b6",
        "on-surface-variant": "#404850",
        "secondary": "#006878",
        "on-error-container": "#93000a",
        "on-error": "#ffffff",
        "primary-fixed-dim": "#94ccff",
        "surface-container-high": "#e6e8ea",
        "surface-container": "#eceef0",
        "on-primary-fixed-variant": "#004b74",
        "background": "#f7f9fb",
        "outline": "#707881",
        "on-surface": "#191c1e",
        "on-secondary-fixed-variant": "#004e5b",
        "on-secondary-fixed": "#001f25",
        "tertiary": "#006176",
        "surface": "#f7f9fb",
        "on-tertiary-fixed": "#001f27",
        "on-background": "#191c1e",
        "inverse-on-surface": "#eff1f3",
        "surface-container-highest": "#e0e3e5",
        "on-secondary-container": "#006575",
        "tertiary-container": "#007c95",
        "primary": "#005d90",
        "secondary-fixed": "#a7edff",
        "inverse-primary": "#94ccff",
        "tertiary-fixed-dim": "#4cd6fb",
        "on-tertiary-fixed-variant": "#004e5f",
        "surface-variant": "#e0e3e5",
        "secondary-container": "#69e5ff",
        // Existing colors
        strava: {
          50: '#fff5f0',
          100: '#ffe8d6',
          200: '#ffd6b8',
          300: '#ffb380',
          400: '#ff8844',
          500: '#FC5200',
          600: '#FE6524',
          700: '#FF7A3D',
          800: '#FF4C00',
          900: '#CC3800',
        },
        ocean: {
          50: '#f0f9ff',
          100: '#e0f2fe',
          200: '#bae6fd',
          300: '#7dd3fc',
          400: '#38bdf8',
          500: '#0ea5e9',
          600: '#0284c7',
          700: '#0369a1',
          800: '#075985',
          900: '#003d7a',
        },
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "xs": "8px",
        "xl": "48px",
        "sm": "16px",
        "lg": "32px",
        "container-margin": "20px",
        "base": "4px",
        "md": "24px",
        "gutter": "16px"
      },
      fontFamily: {
        "sans": ['Inter', 'system-ui', 'sans-serif'],
        "h2": ["Lexend"],
        "h1": ["Lexend"],
        "body-sm": ["Plus Jakarta Sans"],
        "label-md": ["Lexend"],
        "display": ["Lexend"],
        "body-lg": ["Plus Jakarta Sans"],
        "body-md": ["Plus Jakarta Sans"],
        "label-sm": ["Lexend"],
        "h3": ["Lexend"]
      },
      fontSize: {
        "xs": ['0.75rem', { lineHeight: '1rem' }],
        "sm": ['0.875rem', { lineHeight: '1.25rem' }],
        "base": ['1rem', { lineHeight: '1.5rem' }],
        "lg": ['1.125rem', { lineHeight: '1.75rem' }],
        "xl": ['1.25rem', { lineHeight: '1.75rem' }],
        "2xl": ['1.5rem', { lineHeight: '2rem' }],
        "h2": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "h1": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "label-md": ["14px", { "lineHeight": "16px", "letterSpacing": "0.02em", "fontWeight": "500" }],
        "display": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "label-sm": ["12px", { "lineHeight": "14px", "letterSpacing": "0.04em", "fontWeight": "600" }],
        "h3": ["20px", { "lineHeight": "28px", "fontWeight": "500" }]
      },
      animation: {
        'fade-in': 'fadeIn 0.3s ease-in-out',
        'slide-up': 'slideUp 0.3s ease-out',
        'pulse-soft': 'pulseSoft 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'bounce-soft': 'bounceSoft 1s ease-in-out infinite',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { opacity: '0', transform: 'translateY(10px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        pulseSoft: {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.7' },
        },
        bounceSoft: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-5px)' },
        },
      },
      boxShadow: {
        sm: '0 1px 2px 0 rgba(0, 0, 0, 0.05)',
        base: '0 4px 6px -1px rgba(0, 0, 0, 0.1)',
        md: '0 10px 15px -3px rgba(0, 0, 0, 0.1)',
        lg: '0 20px 25px -5px rgba(0, 0, 0, 0.1)',
        xl: '0 25px 50px -12px rgba(0, 0, 0, 0.15)',
        'inner-soft': 'inset 0 2px 4px 0 rgba(0, 0, 0, 0.05)',
      },
    },
  },
  plugins: [],
};
